---

- block:
    - name: stat kibana distribution
      stat:
        path: "{{ elastic_app_dir }}/{{ elastic_kibana_release_name }}/bin/kibana"
      register: t_elastic_kibana_release_stat

    - name: "install kibana {{ elastic_version }}"
      block:
        - name: "download kibana {{ elastic_version }}"
          get_url:
            url: "{{ elastic_kibana_release_url }}"
            checksum: "sha512:{{ elastic_kibana_release_url }}.sha512"
            dest: "{{ elastic_distfiles }}/{{ elastic_kibana_release_archive }}"
            mode: "0644"

        - name: extract kibana distribution
          unarchive:
            remote_src: yes
            src: "{{ elastic_distfiles }}/{{ elastic_kibana_release_archive }}"
            dest: "{{ elastic_app_dir }}"
            mode: "go-w"

      when: not t_elastic_kibana_release_stat.stat.exists

    - name: "link kibana {{ elastic_version }} as default"
      file:
        src: "./{{ elastic_kibana_release_name }}"
        dest: "{{ elastic_app_kibana_dir }}"
        force: yes
        state: link

  when: want_kibana
