---

- block:
    - include: context.yml

    - include: accounts.yml
      vars: {
        accounts_groups: "{{ elastic_groups }}",
        accounts_users: "{{ elastic_users }}"
      }

    - include: workspace.yml

    - include: install.yml

    - include: configure_elasticsearch.yml

    - include: configure_kibana.yml

  when: want_elastic

- name: "set has_elastic to {{ want_elastic }}"
  set_fact:
    has_elastic: "{{ want_elastic }}"
