#!/bin/sh

exec 2>&1

set -e

cd "{{ elastic_elasticsearch_dir }}"

exec setuidgid "{{ elastic_user }}" \
     env ES_HOME="{{ elastic_elasticsearch_dir }}" \
     "{{ elastic_elasticsearch_dir }}/bin/elasticsearch"
